spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - flyway
      - swagger-ui
      - mysql-local
      - security-local

logging:
  level:
    com.hiit.api.domain: DEBUG
