hiit:
  flyway:
    entity:
      locations: classpath:db/migration/entity
      sql-migration-suffixes: sql
      baseline-on-migrate: true
      baseline-version: 0
    batch:
      locations: classpath:db/migration/batch
      sql-migration-suffixes: sql
      baseline-on-migrate: true
      baseline-version: 0
