kakao:
  uri:
    token: ${KAKO_TOKEN_URI}
    token_info: ${KAKO_TOKEN_INFO_URI}
    me_info: ${KAKO_ME_INFO_URI}
  redirect_uri: ${KAKO_APP_REDIRECT_URI}
  client_id: ${KAKO_APP_CLIENT_ID}
  retry:
    period: ${KAKO_RETRY_PERIOD}
    attempts: ${KAKO_RETRY_ATTEMPTS}
