firebase:
  multicast-message:
    size: 500
  projectId: hiit-dev-a8917
  private:
    keyId: ${FIREBASE_PRIVATE_KEY_ID}
    key: ${FIREBASE_PRIVATE_KEY}
  client:
    id: ${FIREBASE_CLIENT_ID}
    email: ${FIREBASE_CLIENT_EMAIL}
  token:
    uri: https://oauth2.googleapis.com/token